### ISSUE TITLE
Update PR comment instead of posting a new one all the time

### ISSUE THREAD

**Issue by rbelling** [rbelling/bundle-checker#55]
I was looking into `danger.js` code, to see how they do it.

https://github.com/danger/danger-js/blob/dae0ead05d35eeaeaf1914b970d8cf5e2e386d44/source/platforms/github/comms/issueCommenter.ts#L133

https://github.com/danger/danger-js/blob/dae0ead05d35eeaeaf1914b970d8cf5e2e386d44/source/platforms/github/GitHubAPI.ts#L85

**Comment by FeliceGeracitano** [comment]
Should be solved by https://github.com/rbelling/bundle-checker/pull/68
