### ISSUE TITLE
Master vs Master has delta > 0

### ISSUE THREAD

**Issue by FeliceGeracitano** [rbelling/bundle-checker#57]
wrong image uploaded...

**Comment by rbelling** [comment]
it's not the same branch though?  `CrossEye-patch-1` vs `master`

**Comment by FeliceGeracitano** [comment]
sorry wrong image

![Screenshot 2019-04-11 at 16 04 25](https://user-images.githubusercontent.com/6695231/55978699-54d40700-5c88-11e9-9455-5cc339d59157.png)

**Comment by FeliceGeracitano** [comment]
fixed: https://github.com/rbelling/bundle-checker/issues/62
