### ISSUE TITLE
Smart file comparision

### ISSUE THREAD

**Issue by FeliceGeracitano** [rbelling/bundle-checker#76]
Explore the possibility to have an output that does not consider hash in the filename:

from:

| File Name | current | target |
| ---------- | ------- | ------ |
| main.abc.js | 0KB | 1KB |  
| main.bcd.js | 1KB | 0KB |  

to:

| File Name | current | target |
| ---------- | ------- | ------ |
| main.[hash].js | 1KB | 1KB |

**Comment by rbelling** [comment]
this should be fixed now
